'use client'

import jsPDF from 'jspdf'

type Counts = Record<string, number>

interface Props {
  totals: {
    totalPpas: number
    gsaPlRecords: number
    avgClassScore: string
    dlpComplianceRate: number
  }
  ppaStatusCounts: Counts
  ppaStatusLabels: Record<string, string>
  dlpImplCounts: Counts
  implLabels: Record<string, string>
  gsaPlByTerm: Counts
  termLabels: Record<string, string>
}

export default function PdfExportButton({
  totals,
  ppaStatusCounts,
  ppaStatusLabels,
  dlpImplCounts,
  implLabels,
  gsaPlByTerm,
  termLabels,
}: Props) {
  function handleExport() {
    const doc = new jsPDF()
    const green: [number, number, number] = [11, 110, 51]
    const dark: [number, number, number] = [30, 41, 59]
    const gray: [number, number, number] = [100, 116, 139]

    doc.setFillColor(...green)
    doc.rect(0, 0, 210, 28, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Research & Innovation HUB', 105, 14, { align: 'center' })
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Schools Division Office of Davao City', 105, 21, { align: 'center' })

    let y = 38
    doc.setTextColor(...gray)
    doc.setFontSize(9)
    const reportDate = new Date().toLocaleDateString('en-PH', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    doc.text(`DMEA Dashboard Report - Generated ${reportDate}`, 105, y, { align: 'center' })

    y += 14
    doc.setTextColor(...dark)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Summary', 14, y)
    y += 8

    const summaryLines: [string, string][] = [
      ['Total PPAs', String(totals.totalPpas)],
      ['GSA/PL Records', String(totals.gsaPlRecords)],
      ['Avg Class Score', totals.avgClassScore],
      ['DLP Compliance Rate', `${totals.dlpComplianceRate}%`],
    ]

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    summaryLines.forEach(([label, value]) => {
      doc.setTextColor(...gray)
      doc.text(`${label}:`, 14, y)
      doc.setTextColor(...dark)
      doc.setFont('helvetica', 'bold')
      doc.text(value, 70, y)
      doc.setFont('helvetica', 'normal')
      y += 7
    })

    y += 6

    function section(title: string, counts: Counts, labels: Record<string, string>, total: number) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(...dark)
      doc.text(title, 14, y)
      y += 8
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)

      const entries = Object.entries(counts)
      if (entries.length === 0) {
        doc.setTextColor(...gray)
        doc.text('No data yet', 14, y)
        y += 10
        return
      }

      entries.forEach(([key, count]) => {
        const pct = total > 0 ? Math.round((count / total) * 100) : 0
        doc.setTextColor(...dark)
        doc.text(`${labels[key] ?? key}`, 14, y)
        doc.text(`${count} (${pct}%)`, 160, y)

        const barWidth = 120
        const filled = (pct / 100) * barWidth
        doc.setFillColor(230, 230, 230)
        doc.rect(14, y + 2, barWidth, 2, 'F')
        doc.setFillColor(...green)
        doc.rect(14, y + 2, filled, 2, 'F')

        y += 10
      })
      y += 4
    }

    section('PPAs by Status', ppaStatusCounts, ppaStatusLabels, totals.totalPpas)

    const dlpTotal = Object.values(dlpImplCounts).reduce((a, b) => a + b, 0)
    section('DLP Implementation Status', dlpImplCounts, implLabels, dlpTotal)

    section('GSA/PL Records by Term', gsaPlByTerm, termLabels, totals.gsaPlRecords)

    doc.setFontSize(8)
    doc.setTextColor(...gray)
    doc.text('Generated by Research & Innovation HUB', 105, 290, { align: 'center' })

    doc.save(`DMEA_Dashboard_${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  return (
    <button
      onClick={handleExport}
      className="rounded-md bg-white border border-[#0B6E33] text-[#0B6E33] text-sm font-medium px-4 py-2 hover:bg-[#0B6E33] hover:text-white transition-colors"
    >
      Export to PDF
    </button>
  )
}